name: ct312h_project
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_dash: ^1.0.0
  shared_preferences: ^2.5.2
  flutter_dotenv: ^5.2.1
  pocketbase: ^0.22.0
  image_picker: ^1.1.2
  path_provider: ^2.1.1
  loading_animation_widget: ^1.3.0
  http: ^1.3.0
  flutter_native_splash: ^2.4.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/dishes/
    - assets/.env

flutter_native_splash:
  color: "#FFC25F"
  image: "assets/logo1.png"
  
  android_12:
    color: "#FFC25F"
    image: "assets/logo1.png"
    # brandings: ""
  
  android: true